In [1]:
import torch

In [2]:
x = torch.arange(4.0)

In [3]:
x

tensor([0., 1., 2., 3.])

In [4]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [5]:
x.grad

In [6]:
y = 2 * torch.dot(x, x)

In [7]:
y

tensor(28., grad_fn=<MulBackward0>)

In [9]:
y.backward()

In [10]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [11]:
x.grad == 4 * x

tensor([True, True, True, True])

In [12]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])