In [1]:
import torch

In [2]:
y = torch.tensor([0, 2])

In [3]:
y

tensor([0, 2])

In [4]:
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])

In [5]:
y_hat

tensor([[0.1000, 0.3000, 0.6000],
        [0.3000, 0.2000, 0.5000]])

In [6]:
y_hat[[0, 1], y]

tensor([0.1000, 0.5000])

In [9]:
def cross_entropy(y_hat, y):
    return - torch.log(y_hat[range(len(y_hat)), y])

In [10]:
cross_entropy(y_hat, y)

tensor([2.3026, 0.6931])