In [4]:
import numpy as np

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(5).shape

(5,)

In [7]:
np.ones(5).tolist()

[1.0, 1.0, 1.0, 1.0, 1.0]

In [8]:
np.array([1.0,2,3,4,5])

array([1., 2., 3., 4., 5.])

In [9]:
np.array([1,2,3,4,5], dtype='float')

array([1., 2., 3., 4., 5.])

In [10]:
np.array([x for x in range(20) if x % 2 == 0])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.random.random(10)

array([0.37682549, 0.02269507, 0.77802457, 0.47969173, 0.77812311,
       0.93451228, 0.27258139, 0.43943325, 0.65141285, 0.91381548])

In [14]:
np.random.randint(5, 15, size=10)

array([ 9,  6,  7,  7, 12,  9,  6,  7,  8, 13])

In [15]:
x = np.array([10, 20, 30, 40, 50])

In [16]:
x

array([10, 20, 30, 40, 50])

In [17]:
x[0]

10

In [18]:
x[0:2]

array([10, 20])

In [19]:
x[[-1]]

array([50])

In [20]:
x[-3:]

array([30, 40, 50])

In [21]:
x[[0,2,4]]

array([10, 30, 50])

In [22]:
x2 = x.copy()

In [23]:
x2

array([10, 20, 30, 40, 50])

In [24]:
x2[0] = 10

In [25]:
x2

array([10, 20, 30, 40, 50])

In [26]:
x

array([10, 20, 30, 40, 50])

In [27]:
x2[[1,2]] = 10

In [28]:
x2

array([10, 10, 10, 40, 50])

In [30]:
x2[[3,4]] = [0, 1]

In [31]:
x2

array([10, 10, 10,  0,  1])

In [32]:
x

array([10, 20, 30, 40, 50])

In [33]:
x.sum()

150

In [34]:
x.mean()

30.0

In [35]:
x.max()

50

In [36]:
x.min()

10

In [37]:
x.argmax()

4

In [38]:
x.argmin()

0

In [39]:
np.log(x)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [40]:
np.exp(x)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [42]:
x + x

array([ 20,  40,  60,  80, 100])

In [43]:
x + 1

array([11, 21, 31, 41, 51])

In [45]:
# log every value as list, one by one
def listlog(vals):
    return [np.log(y) for y in vals]

In [46]:

# get random vector
samp = np.random.random_sample(int(1e7))+1
samp

array([1.76999774, 1.71202126, 1.40208285, ..., 1.04619966, 1.51752717,
       1.28109532])

In [48]:
%time _ = np.log(samp)

CPU times: user 0 ns, sys: 1.16 s, total: 1.16 s
Wall time: 1.17 s


In [49]:
%time _ = listlog(samp)

CPU times: user 6.29 s, sys: 681 ms, total: 6.97 s
Wall time: 6.97 s


# Matrices

In [50]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.array([[1,2,3], [4,5,6]], dtype='float')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [52]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [56]:
X = np.array([[1,2,3], [4,5,6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
X[0]

array([1, 2, 3])

In [58]:
X[0,0]

1

In [59]:
X[:, 0]

array([1, 4])

In [60]:
X[0, :]

array([1, 2, 3])

In [61]:
X[:, [0,2]]

array([[1, 3],
       [4, 6]])

In [62]:
X

array([[1, 2, 3],
       [4, 5, 6]])

## Matrix assignment

In [63]:
# X2 = X # try this line instead
X2 = X.copy()

X2

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
X2[0,0] = 20

X2

array([[20,  2,  3],
       [ 4,  5,  6]])

In [65]:
X2[0] = 3

X2

array([[3, 3, 3],
       [4, 5, 6]])

In [66]:
X2[: , -1] = [5, 6]

X2

array([[3, 3, 5],
       [4, 5, 6]])

In [67]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
z = np.arange(1, 7)

In [69]:
z

array([1, 2, 3, 4, 5, 6])

In [70]:
z.shape

(6,)

In [71]:
Z = z.reshape(2, 3)

In [72]:
Z

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
Z.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [74]:
Z.flatten()

array([1, 2, 3, 4, 5, 6])

In [75]:
Z.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [76]:
A = np.array(range(1,7), dtype='float').reshape(2,3)

A

array([[1., 2., 3.],
       [4., 5., 6.]])

In [77]:
A = np.array(range(1,7), dtype='float').reshape(2,3)

In [78]:
A

array([[1., 2., 3.],
       [4., 5., 6.]])

In [79]:
B = np.array([1, 2, 3])

In [80]:
B

array([1, 2, 3])

In [81]:
A * B

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [82]:
A + B

array([[2., 4., 6.],
       [5., 7., 9.]])

In [83]:
A / B

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [84]:
A.dot(B)

array([14., 32.])

In [85]:
array([14., 32.])

NameError: name 'array' is not defined

In [86]:
B.dot(A.T)

array([14., 32.])

In [87]:
A

array([[1., 2., 3.],
       [4., 5., 6.]])

In [88]:
B

array([1, 2, 3])

In [89]:
B.shape

(3,)

In [90]:
A.dot(A.T)

array([[14., 32.],
       [32., 77.]])

In [91]:
B

array([1, 2, 3])

In [92]:
np.outer(B, B)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])